# Generated by Django 3.1 on 2023-01-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230120_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
